const state = { currentUser: 'GUEST', path: 'C:/', history: [], sanityLevel: 100, reads: {}, unlockedCam15: false, youCreated: false };
const bootLines = ['TARRANT BIOS 09.15', 'Verificando memória: 640K OK', 'Montando C:/RECORDS ... OK', 'Sincronizando relógio clínico ... FALHA', 'Carregando rabbit.exe ... recusado', 'Inicializando interface comprometida ...', ''];
const fs = {
  'C:/': { type: 'dir', children: ['USERS', 'RECORDS', 'EXPERIMENTS', 'CAMERAS', 'SYSTEM', 'TEMP', 'LOST', 'AUDIO', 'ARCHIVE', 'TRASH', '███████', 'rabbit.exe', '.REMEMBER', '.NULL', '.DELETED', '.REWRITE', '.MEM'] },
  'C:/USERS': { type: 'dir', children: ['GUEST', 'ARCHIVIST'] },
  'C:/USERS/GUEST': { type: 'dir', children: ['desktop.ini', 'session.log'] },
  'C:/USERS/GUEST/session.log': { type: 'text', body: 'Sessão convidada. Acesso reduzido. O sistema registra hesitação, horários e repetição de leitura.' },
  'C:/USERS/GUEST/desktop.ini': { type: 'text', body: 'wallpaper=CORRIDOR_EAST\nclock=trusted:false\npatient_overlay=disabled' },
  'C:/USERS/ARCHIVIST': { type: 'dir', hidden: true, children: ['credentials.hint', 'audit.log'] },
  'C:/USERS/ARCHIVIST/credentials.hint': { type: 'text', body: 'Senha não é nome. Não é data direta. Inverta o horário do relatório 03:06 e leia como protocolo.' },
  'C:/USERS/ARCHIVIST/audit.log': { type: 'text', body: 'DR_TARRANT alterou 19 arquivos após o óbito. A palavra CURA aparece 43 vezes. A palavra CULPA aparece 0 vezes.' },
  'C:/RECORDS': { type: 'dir', children: ['patient_15.txt', 'intake_15.txt', 'mother_case.txt', 'mirror_note.txt'] },
  'C:/RECORDS/patient_15.txt': { type: 'mutable', versions: ['Paciente 15: Alice L. confessou participação direta na morte da mãe. Memória resistente.', 'Paciente 15: Alice L. viu a mãe morrer. A confissão foi induzida durante privação de sono.', 'Paciente 15: Alice L. nunca esteve na cozinha. O relatório anterior foi reescrito por ordem superior.', 'POR QUE VOCÊ CONTINUA LENDO ISSO?'] },
  'C:/RECORDS/intake_15.txt': { type: 'text', body: 'Entrada: 15 anos. Sintomas: lacunas, culpa implantada, resposta extrema a coelhos brancos, recusa de espelhos.' },
  'C:/RECORDS/mother_case.txt': { type: 'mutable', versions: ['Caso encerrado. Filha culpada. Instituto autorizado a tratar.', 'Caso suspenso. Evidência fotográfica incompatível com o depoimento.', 'Caso inexistente no registro civil local. Quem assinou a autorização?'] },
  'C:/RECORDS/mirror_note.txt': { type: 'text', body: 'Espelhos removidos após o incidente LOOKDOWN. Paciente descreveu o observador como você.' },
  'C:/EXPERIMENTS': { type: 'dir', children: ['REWRITE.protocol', 'dose_table.csv', 'sleep_room.video', 'PATIENT15.lock'] },
  'C:/EXPERIMENTS/REWRITE.protocol': { type: 'text', body: 'Objetivo: substituir memória traumática por culpa administrável. Se a culpa estabiliza a paciente, a verdade é clinicamente irrelevante.' },
  'C:/EXPERIMENTS/dose_table.csv': { type: 'text', body: '03:06,red,15mg\n06:30,white,0mg\n09:15,green,REDACTED\nA coluna verde é uma senha apenas para quem percebe ordem invertida.' },
  'C:/EXPERIMENTS/sleep_room.video': { type: 'video', body: 'FITA 09:15 — a cama está vazia, mas a respiração está perto do microfone.' },
  'C:/EXPERIMENTS/PATIENT15.lock': { type: 'locked', pass: '915', body: 'Desbloqueado: CAM_15 pode ser chamada pelo terminal. A imagem não pertence ao prédio.' },
  'C:/CAMERAS': { type: 'dir', children: ['CAM_01.feed', 'CAM_04.feed', 'CAM_09.feed', 'CAM_12.feed'] },
  'C:/CAMERAS/CAM_01.feed': { type: 'image', body: 'CORREDOR LESTE — vazio por 11 horas.' },
  'C:/CAMERAS/CAM_04.feed': { type: 'image', body: 'QUARTO 15 — a cadeira mudou de lugar entre frames.' },
  'C:/CAMERAS/CAM_09.feed': { type: 'image', body: 'LABORATÓRIO — luz cirúrgica acesa sem operador.' },
  'C:/CAMERAS/CAM_12.feed': { type: 'image', body: 'ALA PROIBIDA — sinal dobrado sobre si mesmo.' },
  'C:/SYSTEM': { type: 'dir', children: ['kernel.log', 'antivirus.exe', 'clock.drift', 'permissions.sys'] },
  'C:/SYSTEM/kernel.log': { type: 'text', body: 'sanityLevel is not user-facing. decrement on contradiction, mirror command, repeated patient file access.' },
  'C:/SYSTEM/antivirus.exe': { type: 'text', body: 'TARRANT SAFE: 0 ameaças. 1 paciente. 1 observador. O observador ainda acredita que está fora.' },
  'C:/SYSTEM/clock.drift': { type: 'text', body: 'O relógio quebra em 03:06, 09:15 e quando o usuário entende que YOU é diretório.' },
  'C:/SYSTEM/permissions.sys': { type: 'text', body: 'GUEST: read public. ARCHIVIST: hidden paths. DR_TARRANT: rewrite records. YOU: treatment complete.' },
  'C:/TEMP': { type: 'dir', children: ['breath.tmp', 'radio.tmp', 'metal.tmp'] },
  'C:/TEMP/breath.tmp': { type: 'audio', body: 'Áudio: respiração muito próxima, 14 segundos, canal esquerdo.' },
  'C:/TEMP/radio.tmp': { type: 'audio', body: 'Áudio: rádio distante repetindo “ela não assinou”.' },
  'C:/TEMP/metal.tmp': { type: 'audio', body: 'Áudio: metal arrastando no andar de cima.' },
  'C:/LOST': { type: 'dir', children: ['found_footage.gif', 'apology.txt'] },
  'C:/LOST/found_footage.gif': { type: 'video', body: 'GIF: três frames do corredor. No terceiro, há uma silhueta baixa demais.' },
  'C:/LOST/apology.txt': { type: 'mutable', versions: ['Desculpe, Alice.', 'Desculpe, paciente.', 'Desculpe, usuário.', 'Tratamento quase concluído.'] },
  'C:/AUDIO': { type: 'dir', children: ['reverse_0915.wav', 'intercom_wardB.wav'] },
  'C:/AUDIO/reverse_0915.wav': { type: 'audio', body: 'Metadata: created 09:15. Reverso sugerido: 519. Não é senha final; é uma direção.' },
  'C:/AUDIO/intercom_wardB.wav': { type: 'audio', body: '“Todos os pacientes devem retornar aos quartos. Exceto você.”' },
  'C:/ARCHIVE': { type: 'dir', children: ['emails.bak', 'photograph.meta', 'treatment_complete.txt'] },
  'C:/ARCHIVE/emails.bak': { type: 'text', body: 'Backup parcial: 37 mensagens; 12 deletadas; 4 enviadas após a morte do remetente.' },
  'C:/ARCHIVE/photograph.meta': { type: 'text', body: 'exposure=3; subject=empty_chair; corner_digits=9-1-5; note=senha vem de timestamp, não de aniversário.' },
  'C:/ARCHIVE/treatment_complete.txt': { type: 'locked', pass: 'MIRROR', body: 'Se você está lendo isto, o sistema já escreveu seu diretório.' },
  'C:/TRASH': { type: 'dir', children: ['deleted_mail_01.eml', 'deleted_mail_02.eml', 'not_a_confession.txt'] },
  'C:/TRASH/deleted_mail_01.eml': { type: 'text', body: 'Assunto: apagar autorização\nNão temos assinatura legal. Use a confissão como substituto.' },
  'C:/TRASH/deleted_mail_02.eml': { type: 'text', body: 'Assunto: câmera 15\nA câmera não foi instalada por manutenção. Ela apareceu no mapa às 03:06.' },
  'C:/TRASH/not_a_confession.txt': { type: 'text', body: 'Eu disse que vi. Eles escreveram que fiz. — A.' },
  'C:/███████': { type: 'dir', children: ['red_room.txt'] },
  'C:/███████/red_room.txt': { type: 'text', body: 'A sala vermelha não está no Instituto. Está atrás da tela.' },
  'C:/rabbit.exe': { type: 'exec', body: 'rabbit.exe correu. Uma janela abriu antes de existir.' },
  'C:/.REMEMBER': { type: 'dir', hidden: true, children: ['first_memory.txt'] },
  'C:/.REMEMBER/first_memory.txt': { type: 'mutable', versions: ['A primeira memória é uma faca.', 'A primeira memória é uma porta.', 'A primeira memória é alguém mandando Alice lembrar errado.'] },
  'C:/.NULL': { type: 'dir', hidden: true, children: ['empty.txt'] },
  'C:/.NULL/empty.txt': { type: 'text', body: 'O vazio ainda tem dono.' },
  'C:/.DELETED': { type: 'dir', hidden: true, children: ['mother_voice.wav'] },
  'C:/.DELETED/mother_voice.wav': { type: 'audio', body: '“Alice, corra. Não para fora. Para dentro.”' },
  'C:/.REWRITE': { type: 'dir', hidden: true, children: ['script.js.note'] },
  'C:/.REWRITE/script.js.note': { type: 'text', body: 'console.log não é pista no site oficial. Aqui é.' },
  'C:/.MEM': { type: 'dir', hidden: true, children: ['you.seed'] },
  'C:/.MEM/you.seed': { type: 'text', body: 'Quando WHOAMI mentir três vezes, crie USERS/YOU.' }
};
const emails = Array.from({ length: 24 }, (_, i) => ({ subject: `Relatório administrativo ${String(i + 1).padStart(2, '0')}`, from: i % 3 ? 'admin@tarrant.local' : 'dr.tarrant@tarrant.local', body: i % 5 === 0 ? 'Anexo removido. O conteúdo contradizia o prontuário de Alice.' : 'Rotina clínica, doses aprovadas, linguagem cuidadosamente impessoal.' })).concat([
  { subject: 'URGENTE: paciente 15', from: 'nurse.elias@tarrant.local', body: 'Ela não confessou. Ela repetiu a frase depois do áudio tocar 31 vezes.' },
  { subject: 'RE: URGENTE', from: 'dr.tarrant@tarrant.local', body: 'Então registre como progresso.' },
  { subject: '[DELETADO] câmera que não existe', from: 'security@tarrant.local', body: 'CAM_15 transmite um quarto que não temos. Há alguém sentado diante do monitor.' },
  { subject: 'sem assunto', from: 'alice@nowhere', body: 'se você está lendo, pare de deixar que ele escolha a primeira versão.' }
]);

const boot = document.getElementById('boot'); const login = document.getElementById('login'); const desktop = document.getElementById('desktop'); const bootLog = document.getElementById('boot-log'); const pathInput = document.getElementById('path-input'); const fileList = document.getElementById('file-list'); const viewer = document.getElementById('file-viewer'); const termOut = document.getElementById('terminal-output'); const termInput = document.getElementById('terminal-input');
let line = 0;
const bootTimer = setInterval(() => { bootLog.textContent += `${bootLines[line] || 'Sistema pronto.'}\n`; line += 1; if (line > bootLines.length) { clearInterval(bootTimer); boot.classList.add('hidden'); login.classList.remove('hidden'); } }, 420);

document.getElementById('login-button').addEventListener('click', () => { const user = document.getElementById('login-user').value; const pass = document.getElementById('login-pass').value.trim().toUpperCase(); if (user === 'GUEST' || (user === 'ARCHIVIST' && pass === '915') || (user === 'DR_TARRANT' && pass === 'REWRITE')) { state.currentUser = user; login.classList.add('hidden'); desktop.classList.remove('hidden'); openWindow('explorer-window'); renderExplorer('C:/'); notify(`Sessão iniciada: ${user}`); } else { document.getElementById('login-hint').textContent = 'Credencial rejeitada. Datas diretas não curam ninguém.'; reduceSanity(5); } });
document.querySelectorAll('[data-open]').forEach(btn => btn.addEventListener('click', () => { const id = `${btn.dataset.open}-window`; if (btn.dataset.open === 'trash') renderExplorer('C:/TRASH'); else openWindow(id); if (btn.dataset.open === 'mail') renderMail(); if (btn.dataset.open === 'cameras') renderCameras(); if (btn.dataset.open === 'processes') renderProcesses(); }));
document.querySelectorAll('[data-close]').forEach(btn => btn.addEventListener('click', () => document.getElementById(btn.dataset.close).classList.add('hidden')));
function openWindow(id) { const win = document.getElementById(id); if (win) win.classList.remove('hidden'); }

document.getElementById('go-button').addEventListener('click', () => renderExplorer(pathInput.value)); document.getElementById('back-button').addEventListener('click', () => { const previous = state.history.pop(); if (previous) renderExplorer(previous, true); }); pathInput.addEventListener('keydown', e => { if (e.key === 'Enter') renderExplorer(pathInput.value); });
function normalize(path) { let p = path.trim().replaceAll('\\', '/'); if (!p.toUpperCase().startsWith('C:/')) p = `C:/${p}`; return p.replace(/\/+/g, '/').replace(/\/$/, '') || 'C:/'; }
function renderExplorer(path, fromBack = false) { const normalized = normalize(path); const node = fs[normalized]; openWindow('explorer-window'); if (!node) { viewer.textContent = 'Caminho não encontrado. Alguns caminhos existem apenas quando você admite que está procurando.'; reduceSanity(2); return; } if (!fromBack && state.path !== normalized) state.history.push(state.path); state.path = normalized; pathInput.value = normalized; if (node.type !== 'dir') { openFile(normalized); return; } fileList.innerHTML = ''; node.children.filter(child => !child.startsWith('.')).forEach(child => { const full = normalized === 'C:/' ? `C:/${child}` : `${normalized}/${child}`; const item = document.createElement('button'); item.className = 'file-item'; item.innerHTML = `<span>${fs[full]?.type === 'dir' ? '📁' : iconFor(fs[full]?.type)}</span>${child}`; item.addEventListener('click', () => fs[full]?.type === 'dir' ? renderExplorer(full) : openFile(full)); fileList.appendChild(item); }); viewer.textContent = `${normalized}\n${node.children.filter(c => !c.startsWith('.')).length} itens visíveis. Itens ocultos exigem caminho manual ou terminal.`; }
function iconFor(type) { return ({ text: '📄', mutable: '▤', image: '▧', audio: '♫', video: '▣', exec: '▶', locked: '🔒' })[type] || '□'; }
function openFile(path) { const node = fs[path]; pathInput.value = path; state.reads[path] = (state.reads[path] || 0) + 1; if (node.type === 'mutable') { const text = node.versions[Math.min(state.reads[path] - 1, node.versions.length - 1)]; viewer.textContent = `${path}\n\n${text}`; reduceSanity(8); if (state.reads[path] > 2) scheduleEvent(); return; } if (node.type === 'locked') { viewer.innerHTML = `${path}\n\nArquivo protegido. Use DECRYPT ${path} [CHAVE] no terminal.`; return; } if (node.type === 'image') viewer.innerHTML = `<div class="image-file">${node.body}</div>`; else if (node.type === 'audio') viewer.innerHTML = `<p class="audio-file">${node.body}</p><button onclick="beepPattern()">Reproduzir ruído</button>`; else if (node.type === 'video') viewer.innerHTML = `<div class="video-file">${node.body}</div>`; else if (node.type === 'exec') { viewer.textContent = node.body; secretCommand('RABBIT'); } else viewer.textContent = `${path}\n\n${node.body}`; }

termInput.addEventListener('keydown', e => { if (e.key === 'Enter') { const raw = termInput.value.trim(); termInput.value = ''; print(`C:/> ${raw}`); runCommand(raw); } });
function print(text) { const p = document.createElement('p'); p.textContent = text; termOut.appendChild(p); termOut.scrollTop = termOut.scrollHeight; }
function runCommand(raw) { const [cmdRaw, ...args] = raw.split(' '); const cmd = (cmdRaw || '').toUpperCase(); if (!cmd) return; const arg = args.join(' '); if (['RABBIT','WAKEUP','LOOKDOWN','REMEMBER','MIRROR','PATIENT15'].includes(cmd)) return secretCommand(cmd, arg); switch (cmd) { case 'HELP': print('HELP DIR CD TREE OPEN RUN LOGIN WHOAMI CLEAR TRACE RECOVER DECRYPT'); break; case 'DIR': renderExplorer(arg || state.path); print((fs[normalize(arg || state.path)]?.children || []).filter(c => !c.startsWith('.')).join('  ')); break; case 'CD': renderExplorer(arg || 'C:/'); break; case 'TREE': print(tree(normalize(arg || state.path), 0, false)); break; case 'OPEN': openFile(normalize(arg)); break; case 'RUN': openFile(normalize(arg)); break; case 'LOGIN': print('Use tela de login ou LOGIN ARCHIVIST 915. Algumas credenciais são interpretação, não memorização.'); break; case 'WHOAMI': print(`Você é ${state.currentUser}. Não é o suficiente.`); reduceSanity(4); break; case 'CLEAR': termOut.innerHTML = ''; break; case 'TRACE': print('trace: usuário observado desde boot. ponteiro, leituras, hesitações: gravando.'); reduceSanity(6); break; case 'RECOVER': print('Pastas candidatas: .REMEMBER .DELETED .MEM'); reduceSanity(3); break; case 'DECRYPT': decrypt(args); break; default: print('Comando não reconhecido ou deliberadamente escondido.'); reduceSanity(1); } }
function tree(path, depth, includeHidden) { const node = fs[path]; if (!node || node.type !== 'dir' || depth > 4) return path; return [path].concat(node.children.filter(c => includeHidden || !c.startsWith('.')).map(c => `${'  '.repeat(depth + 1)}└ ${c}${fs[path === 'C:/' ? `C:/${c}` : `${path}/${c}`]?.type === 'dir' ? '\n' + tree(path === 'C:/' ? `C:/${c}` : `${path}/${c}`, depth + 2, includeHidden) : ''}`)).join('\n'); }
function decrypt(args) { const key = args.pop()?.toUpperCase(); const path = normalize(args.join(' ')); const node = fs[path]; if (node?.type === 'locked' && key === node.pass) { viewer.textContent = `${path}\n\n${node.body}`; print('DECRYPT OK'); if (path.includes('PATIENT15')) state.unlockedCam15 = true; reduceSanity(10); } else { print('DECRYPT FAILED'); reduceSanity(4); } }
function secretCommand(cmd) { reduceSanity(12); if (cmd === 'RABBIT') { print('rabbit.exe: siga o atraso. 09:15 não é hora, é chave.'); popup('rabbit.exe', 'processo sem assinatura iniciado'); } if (cmd === 'WAKEUP') { print('Acordar não encerra o tratamento.'); desktop.classList.add('screen-flash'); setTimeout(() => desktop.classList.remove('screen-flash'), 220); } if (cmd === 'LOOKDOWN') { print('Há uma pasta abaixo do C:/ que a interface não lista: .MEM'); renderExplorer('C:/.MEM'); } if (cmd === 'REMEMBER') { print(tree('C:/.REMEMBER', 0, true)); renderExplorer('C:/.REMEMBER'); } if (cmd === 'MIRROR') { print('O espelho criou C:/USERS/YOU/'); createYou(); renderExplorer('C:/USERS/YOU'); } if (cmd === 'PATIENT15') { state.unlockedCam15 = true; print('CAM_15 registrada por 15 segundos. Ela está olhando para o operador.'); renderCameras(); } }
function createYou() { if (state.youCreated) return; state.youCreated = true; const now = new Date(); fs['C:/USERS'].children.push('YOU'); fs['C:/USERS/YOU'] = { type: 'dir', children: ['browser.log', 'real_time.txt', 'treatment_complete.txt', 'personal.txt'] }; fs['C:/USERS/YOU/browser.log'] = { type: 'text', body: `Origem: ${location.href}\nAgente: ${navigator.userAgent}\nO jogador abriu a porta sem senha direta.` }; fs['C:/USERS/YOU/real_time.txt'] = { type: 'text', body: `Horário real registrado: ${now.toString()}\nO relógio do sistema discorda.` }; fs['C:/USERS/YOU/treatment_complete.txt'] = { type: 'text', body: 'TRATAMENTO CONCLUÍDO. O paciente aceitou que a verdade muda quando observada.' }; fs['C:/USERS/YOU/personal.txt'] = { type: 'mutable', versions: ['Você começou acreditando que Alice era culpada.', 'Você continuou lendo depois que os arquivos mudaram.', 'Você também é parte do prontuário.'] }; }

function renderMail() { const list = document.getElementById('mail-list'); const view = document.getElementById('mail-view'); list.innerHTML = ''; emails.forEach((mail, i) => { const li = document.createElement('li'); li.textContent = `${mail.subject}\n${mail.from}`; li.addEventListener('click', () => { view.textContent = `DE: ${mail.from}\nASSUNTO: ${mail.subject}\n\n${mail.body}`; if (i > 24) reduceSanity(5); }); list.appendChild(li); }); }
function renderCameras() { const tabs = document.getElementById('camera-tabs'); const feed = document.getElementById('camera-feed'); const cams = ['CAM_01','CAM_04','CAM_09','CAM_12'].concat(state.unlockedCam15 ? ['CAM_15'] : []); tabs.innerHTML = ''; cams.forEach(cam => { const b = document.createElement('button'); b.textContent = cam; b.addEventListener('click', () => { const entity = cam === 'CAM_15' || (Math.random() > .82 && state.sanityLevel < 70); feed.classList.toggle('entity', entity); feed.querySelector('span').textContent = `${cam} / ${entity ? 'QUARTO QUE NÃO EXISTE' : 'INSTITUTO TARRANT'}`; feed.querySelector('em').textContent = entity ? 'MOVIMENTO DETECTADO ATRÁS DE VOCÊ' : ['corredor vazio', 'sombra incompatível', 'áudio sem imagem', 'porta abriu sozinha'][Math.floor(Math.random()*4)]; if (entity) reduceSanity(9); }); tabs.appendChild(b); }); }
function renderProcesses() { const rows = [['kernel.exe','3%','OK'], ['rabbit.exe','15%','sem assinatura'], ['tarrant_safe.exe','9%','0 ameaças'], ['rewrite_service','43%','alterando registros'], ['you_watcher','??','ativo']]; document.getElementById('process-list').innerHTML = rows.map(r => `<div class="process-row ${r[1]==='??'||r[0].includes('rewrite')?'bad':''}"><span>${r[0]}</span><span>${r[1]}</span><span>${r[2]}</span></div>`).join(''); }
function reduceSanity(amount) { state.sanityLevel = Math.max(0, state.sanityLevel - amount); desktop.dataset.sanity = state.sanityLevel; document.getElementById('status-text').textContent = state.sanityLevel > 70 ? 'sanidade: estável' : state.sanityLevel > 35 ? 'sanidade: comprometida' : 'sanidade: NÃO CONFIE'; if (state.sanityLevel < 68) desktop.classList.add('corrupt'); if (state.sanityLevel < 45 && Math.random() > .55) scheduleEvent(); if (state.sanityLevel < 20) fakeBsod(); }
function scheduleEvent() { setTimeout(() => { const events = [() => popup('Erro de memória', 'Um arquivo foi alterado enquanto estava aberto.'), () => openWindow('terminal-window'), () => print('> escrita automática: ela não fez isso / ela fez / você escolhe'), () => renderCameras(), () => desktop.classList.add('screen-flash')]; events[Math.floor(Math.random()*events.length)](); setTimeout(() => desktop.classList.remove('screen-flash'), 240); }, 500 + Math.random() * 1800); }
function popup(title, text) { const p = document.createElement('div'); p.className = 'popup'; p.innerHTML = `<strong>${title}</strong><br>${text}<br><button>OK</button>`; p.querySelector('button').addEventListener('click', () => p.remove()); document.getElementById('popup-stack').appendChild(p); setTimeout(() => p.remove(), 9000); }
function fakeBsod() { const b = document.getElementById('bsod'); b.classList.remove('hidden'); const hide = () => { b.classList.add('hidden'); window.removeEventListener('keydown', hide); reduceSanity(-20); }; window.addEventListener('keydown', hide); }
function beepPattern() { const ctx = new (window.AudioContext || window.webkitAudioContext)(); [90, 120, 80, 160].forEach((f, i) => { const o = ctx.createOscillator(); const g = ctx.createGain(); o.frequency.value = f; o.type = 'square'; g.gain.value = .03; o.connect(g).connect(ctx.destination); o.start(ctx.currentTime + i * .14); o.stop(ctx.currentTime + i * .14 + .09); }); }
setInterval(() => { const now = new Date(); let text = now.toLocaleTimeString('pt-BR'); if (state.sanityLevel < 55 && Math.random() > .72) text = '03:06:15'; document.getElementById('clock').textContent = text; }, 1000);
document.addEventListener('pointermove', e => { document.documentElement.style.setProperty('--mx', `${e.clientX}px`); document.documentElement.style.setProperty('--my', `${e.clientY}px`); });
setInterval(() => { if (!desktop.classList.contains('hidden') && Math.random() > .78) popup('TARRANT SAFE', Math.random() > .5 ? 'Nenhuma ameaça detectada. Pare de procurar.' : 'Processo YOU_WATCHER não pode ser encerrado.'); }, 26000);
console.log('%cC:/.REWRITE não aparece no Explorer. TRACE antes de confiar.', 'color:#78ff9a;background:#000;font-size:18px;padding:8px');
